# Generated by Django 2.0.5 on 2018-07-21 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180722_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 22, 7, 9, 996541, tzinfo=utc)),
        ),
    ]
