# Generated by Django 2.0.5 on 2018-07-22 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180722_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 6, 41, 3, 171272, tzinfo=utc)),
        ),
    ]
