# Generated by Django 2.0.5 on 2018-07-22 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180722_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 15, 16, 53, 189402, tzinfo=utc)),
        ),
    ]
